# OAuth2.0 Params
discovered_api: calendar
verision : v3
scope: https://www.googleapis.com/auth/calendar

development:
  redirect_uri: XXXXXXXXXX
  client_id: XXXXXXXXXX
  client_secret: XXXXXXXXXX

# for Heroku
production:
  redirect_uri: XXXXXXXXXX
  client_id: XXXXXXXXXX
  client_secret: XXXXXXXXXX

#calenderApi Params
cal_api_orderBy: startTime
cal_api_sortOrder: ascending
cal_api_maxResults: 9999
cal_api_single_events: true
cal_api_timezone: Asia/Tokyo
cal_api_fields: items(summary,description,start,end)