#OAuth2.0 Params
discovered_api: calendar
verision : v3
scope: https://www.googleapis.com/auth/calendar

development:
  redirect_uri: http://localhost:3000/taskManagement/oauth2callback
  client_id: 846777061871.apps.googleusercontent.com
  client_secret: Kc7jhBXrPJbZvp8LLFGMrAVD

production:
  redirect_uri: http://www.ruby.cloud.com/training/taskManagement/oauth2callback
  client_id: 846777061871-k1coupepin7fd6firah1b0a0cco5v4r8.apps.googleusercontent.com
  client_secret: l-AoqInn4OR5DeSQCHYL4PMP

#calenderApi Params
cal_api_orderBy: startTime
cal_api_sortOrder: ascending
cal_api_maxResults: 9999
cal_api_single_events: true
cal_api_timezone: Asia/Tokyo
cal_api_fields: items(summary,description,start,end)